### ISSUE TITLE
"live" in d2c-edit.js

### ISSUE THREAD

**Issue by cekk** [collective/uwosh.pfg.d2c#19]
Hi,
i've found that in d2c-edit.js there is a "live" event.
For default Plone 4's jquery (1.7) it works without problems, but if we use a newer jquery (for example 1.9) this event is deprecated.

Is there a safe way to handle both events (live and on)?

**Comment by vangheem** [comment]
you can replace `live` with the `on` method.

**Comment by keul** [comment]
Will be closed by https://github.com/collective/uwosh.pfg.d2c/pull/23
