### ISSUE TITLE
Other Plone 5 JavaScript issues on Plone 5.0.4

### ISSUE THREAD

**Issue by keul** [collective/uwosh.pfg.d2c#24]
Although this is now working for Plone 5 due to https://github.com/collective/uwosh.pfg.d2c/pull/23 inclusion, there are some JS issues left.
The current installation is keeping the `jsregistry.xml` put the needed JS in the plone-legacy bundle, but it seems not always loaded.

I think we need to define a new bundle/metabundle

**Comment by vangheem** [comment]
shouldn't need that. Maybe we just need a new plone 5 release that fixes some resource registry bugs?

Any idea why it isn't always loading?

**Comment by keul** [comment]
@vangheem no idea why is not loading it and I'm not aware of open Plone bugs about this.
I'm only sure that the JS is OK.

Maybe the legacy bundle is not loaded anymore?

**Comment by davilima6** [comment]
Seems related to this: plone/Products.CMFPlone#1511

Are you testing on 5.0.4 or coredev?

**Comment by keul** [comment]
Thanks @davilima6, I was working on a customer's Plone 5.0.4.
Switching to coredev fix the issue, so we simply have to wait for Plone 5.0.5.

🍻
